app/models.py
from .import login_manager
from . import db
from flask_login import UserMixin,current_user
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Quote:
    def __init__(self,quote,author):
        self.author = author
        self.quote = quote

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'
           
class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    user_id = db.Column(db.String)
    blog = db.Column(db.String)
    comment = db.relationship('Comment', backref='blogs', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Post Title: {self.title}"

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comment = db.Column(db.Text())    

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comment.query.filter_by(blog_id=id).all()
        return comments

    @classmethod
    def delete_comment(cls,id):
        comment = Comment.query.filter_by(id=id).first()
        db.session.delete(comment)
        db.session.commit()

    def __repr__(self):
        return f'Comments: {self.comment}'  

class Subscriber(db.Model):
    __tablename__ = 'subscribers'
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(20))
    email = db.Column(db.String(), unique = True)         

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):

    title = StringField('Author Name', validators=[Required()])
    blog = TextAreaField('Write blog below ...', validators=[Required()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment here...',validators=[Required()])
    submit = SubmitField('Comment')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

simple = SimpleMDE()

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    # # setting config
    from .request import configure_request
    configure_request(app)



    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from ..request import get_quote
from ..models import Quote,Blog,User,Comment
from . forms import BlogForm,CommentForm,UpdateProfile
from flask_login import login_required,current_user
from .. import db

@main.route('/')
def index():

    Quote = get_quote()
    blogs = Blog.query.all()

    return render_template('index.html',quote=Quote,blogs=blogs)

@main.route('/new_blog', methods=['GET', 'POST'])
@login_required
def new_blog():

    title = 'Bloggiez'

    form = BlogForm()
    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        user_id = current_user._get_current_object().id

        blogpost = Blog(blog=blog, title=title, user_id=user_id)
        blogpost.save()

        return redirect(url_for('main.index'))
        
    return render_template('new_blog.html', form=form) 

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)
    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)     

@main.route('/comment/<int:blog_id>', methods=['GET', 'POST'])
@login_required
def comment(blog_id):

    form = CommentForm()
    blog = Blog.query.get(blog_id)
    user = User.query.all()
    comments = Comment.query.filter_by(blog_id=blog_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        blog_id = blog_id
        user_id = current_user._get_current_object().id
        comment = Comment(
            comment=comment,
            blog_id=blog_id,
            user_id=user_id,
            )

        comment.save()
        comments = [comment]
        print(comments)
        return redirect(url_for('new_comment.html', blog_id=blog_id))
    return render_template('new_comment.html', form=form, blog=blog, comments=comments, user=user)


      

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{%block content %}
<div class="container" style="text-align: center;">
  {{macro.display_blogs(blogs)}}
  <div class="card-body">{{macro.display_comments(comments)}}</div>
</div>


<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <blockquote class="blockquote text-center">
      <p class="mb-0">{{quote.quote}}</p>
      <footer class="blockquote-footer"><cite>{{quote.author}}</cite></footer>
    </blockquote>
  </div>
  <div class="col-md-2"></div>
</div>
{% endblock %}

app/templates/macros.html
{% macro display_blogs(blogs) %}
<div class="card-columns">
    {% if blogs %}
    {% for blog in blogs %}
    <div class="container">
        <div class="card">
            <div class="card-body" style="background-color:rgb(93, 212, 192)">
                <p>Author: {{blog.title}}</p>
                <p>Blog Post: {{blog.blog}}</p>
                {% for comment in comments %}
                <p><a href="{{url_for('main.comment',blog_id=comment.blog_id)}}">Comment</a></p>
                {%endfor%}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
</div>
{% endmacro %}

{% macro display_comments(comments) %}
<div class="container">
</div>
<div class="card-columns">
    {% for comment in comments %}
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
            <p>{{comment.comment}}</p>
            <p class="text-center">{{comment.blog.title}}</p>
            <button style="background-color: #fff;border:1px solid #6184D8;color:#000;" type="button" class="btn btn-sm"
                data-toggle="modal" data-target="#deleteCommentModal"><i class="far fa-trash-alt"></i>&nbsp;Delete
                Comment</button>
        </div>
        <div class="modal fade" id="deleteCommentModal" tabindex="-1" role="dialog"
            aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteCommentModalLabel">Delete Comment?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{{url_for('main.delete_comment', id=comment.id)}}" method="POST">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    {% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Scooby blogs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
        </li>   
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">SIGN IN</a></li>
        {%endif%}   
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">SIGN UP</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.new_blog')}}">NEW BLOG</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.subscriber')}}">Subscribe</a>
        </li>        
      </ul>
    </div>
  </nav>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/new_comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<title>{{title}}</title>
<div class="container">

    <div class="col-md-4">

        {{ wtf.quick_form(form) }}
    </div>

</div>

{% endblock %}

app/templates/profile/profile .html
{% extends 'base.html'%}
{% block content %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/particle.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}
<title>{{title}}</title>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %} {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile/update_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/subscribe.html
{% extends 'base.html'%} 
{% import "bootstrap/wtf.html" as wtf %} 
{% block content %}
<div class="container">

    <div class="col-md-4">

        {{ wtf.quick_form(subscriber_form) }}
    </div>

</div>

{% endblock %}